create table if not exists public.price_rules (
  price_id integer generated by default as identity primary key,
  item_code text not null,
  item_label text,
  selection_code text not null,
  selection_label text,
  price_type text not null default 'ADD' check (price_type in ('BASE', 'ADD', 'INCLUDED')),
  price numeric,
  currency text not null default 'EUR',
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.price_rules enable row level security;

drop policy if exists "Dataset viewers can read price_rules" on public.price_rules;
drop policy if exists "Dataset admins can insert price_rules" on public.price_rules;
drop policy if exists "Dataset admins can update price_rules" on public.price_rules;
drop policy if exists "Dataset admins can delete price_rules" on public.price_rules;

create policy "Dataset viewers can read price_rules"
on public.price_rules
for select
to authenticated
using (public.can_view_datasets());

create policy "Dataset admins can insert price_rules"
on public.price_rules
for insert
to authenticated
with check (public.can_edit_datasets());

create policy "Dataset admins can update price_rules"
on public.price_rules
for update
to authenticated
using (public.can_edit_datasets())
with check (public.can_edit_datasets());

create policy "Dataset admins can delete price_rules"
on public.price_rules
for delete
to authenticated
using (public.can_edit_datasets());

select price_id, item_code, item_label, selection_code, selection_label, price_type, price, currency, note
from public.price_rules
order by price_id;
