drop table if exists public.configuration_rules;

create table public.configuration_rules (
  rule_id integer generated by default as identity primary key,
  input_code text not null,
  input_selection text not null,
  output_code text not null,
  output_selection text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.configuration_rules enable row level security;

drop policy if exists "Dataset viewers can read configuration_rules" on public.configuration_rules;
drop policy if exists "Dataset admins can insert configuration_rules" on public.configuration_rules;
drop policy if exists "Dataset admins can update configuration_rules" on public.configuration_rules;
drop policy if exists "Dataset admins can delete configuration_rules" on public.configuration_rules;

create policy "Dataset viewers can read configuration_rules"
on public.configuration_rules
for select
to authenticated
using (public.can_view_datasets());

create policy "Dataset admins can insert configuration_rules"
on public.configuration_rules
for insert
to authenticated
with check (public.can_edit_datasets());

create policy "Dataset admins can update configuration_rules"
on public.configuration_rules
for update
to authenticated
using (public.can_edit_datasets())
with check (public.can_edit_datasets());

create policy "Dataset admins can delete configuration_rules"
on public.configuration_rules
for delete
to authenticated
using (public.can_edit_datasets());

insert into public.configuration_rules (input_code, input_selection, output_code, output_selection)
values
  ('01.CERTIFICATION', 'ATEX', '10.1', '5'),
  ('01.CERTIFICATION', 'ATEX', '10.2', '5'),
  ('01.APPLICATION', 'FOOD', '10.1', '1,2,3,4'),
  ('01.APPLICATION', 'FOOD', '10.2', '1,2,3,4'),
  ('10.1', '3', '10.3', '7'),
  ('10.1', '5', '10.3', '1,2'),
  ('PUMP_CODE', '12.1,12.2,25.1,25.2,50.1,50.2,50L.1', '10.4', '1'),
  ('PUMP_CODE', '80.1,80.2,200.1,200.2,300.1,300.2,350.1,350.2,350L.1,7032.1,7052.1,7082.1,7112.1,7115.1,7115.2,7115.4,7120.1,7120.2,7120.4', '10.4', '2');

select rule_id, input_code, input_selection, output_code, output_selection
from public.configuration_rules
order by rule_id;
