create table if not exists public.configuration_rules (
  rule_id integer generated by default as identity primary key,
  rule_order integer not null default 100,
  is_active boolean not null default true,
  input_code text not null,
  input_selection text not null,
  output_code_1 text,
  output_selection_1 text,
  output_code_2 text,
  output_selection_2 text,
  output_code_3 text,
  output_selection_3 text,
  output_code_4 text,
  output_selection_4 text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.configuration_rules enable row level security;

drop policy if exists "Dataset viewers can read configuration_rules" on public.configuration_rules;
drop policy if exists "Dataset admins can insert configuration_rules" on public.configuration_rules;
drop policy if exists "Dataset admins can update configuration_rules" on public.configuration_rules;
drop policy if exists "Dataset admins can delete configuration_rules" on public.configuration_rules;

create policy "Dataset viewers can read configuration_rules"
on public.configuration_rules
for select
to authenticated
using (public.can_view_datasets());

create policy "Dataset admins can insert configuration_rules"
on public.configuration_rules
for insert
to authenticated
with check (public.can_edit_datasets());

create policy "Dataset admins can update configuration_rules"
on public.configuration_rules
for update
to authenticated
using (public.can_edit_datasets())
with check (public.can_edit_datasets());

create policy "Dataset admins can delete configuration_rules"
on public.configuration_rules
for delete
to authenticated
using (public.can_edit_datasets());

insert into public.configuration_rules (
  rule_id,
  rule_order,
  is_active,
  input_code,
  input_selection,
  output_code_1,
  output_selection_1,
  output_code_2,
  output_selection_2
)
values
  (1, 10, true, '01.CERTIFICATION', 'ATEX', '10.1', '5', '10.2', '5'),
  (2, 20, true, '01.APPLICATION', 'FOOD', '10.1', '1,2,3,4', '10.2', '1,2,3,4'),
  (3, 30, true, '10.1', '3', '10.3', '7', null, null),
  (4, 40, true, '10.1', '5', '10.3', '1,2', null, null),
  (5, 50, true, 'PUMP_CODE', '12.1,12.2,25.1,25.2,50.1,50.2,50L.1', '10.4', '1', null, null),
  (6, 60, true, 'PUMP_CODE', '80.1,80.2,200.1,200.2,300.1,300.2,350.1,350.2,350L.1,7032.1,7052.1,7082.1,7112.1,7115.1,7115.2,7115.4,7120.1,7120.2,7120.4', '10.4', '2', null, null)
on conflict (rule_id) do update
set
  rule_order = excluded.rule_order,
  is_active = excluded.is_active,
  input_code = excluded.input_code,
  input_selection = excluded.input_selection,
  output_code_1 = excluded.output_code_1,
  output_selection_1 = excluded.output_selection_1,
  output_code_2 = excluded.output_code_2,
  output_selection_2 = excluded.output_selection_2,
  output_code_3 = excluded.output_code_3,
  output_selection_3 = excluded.output_selection_3,
  output_code_4 = excluded.output_code_4,
  output_selection_4 = excluded.output_selection_4,
  updated_at = now();

select *
from public.configuration_rules
order by rule_order, rule_id;
